version: '3.8'

services:
  database:
    container_name: database
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pompe_funebre
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      timeout: 5s

  app:
    build: .
    container_name: nextjs_app
    ports:
      - "3000:3000"
    depends_on:
      database:
        condition: service_healthy
    environment:
      DATABASE_URL: "mysql://admin:admin@database:3306/pompe_funebre"
      NEXTAUTH_URL: "http://localhost:3000"
      JWT_SECRET: "mon_super_secret"
    volumes:
      - "C:/Users/Antoine/Documents/Developpement_Informatique/Projet_Exam_Wild/lesage-lelievre:/app"
      - /app/node_modules
      - /app/.next
      - /app/.turbo

volumes:
  mysql_data:
