version: '3.8'

services:
  database:
    container_name: database # Nom du conteneur MySQL
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pompe_funebre
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: nextjs_app
    ports:
      - "3000:3000"
    depends_on:
      - database
    environment:
      DATABASE_URL: "mysql://admin:admin@database:3306/pompe_funebre"
      NEXTAUTH_URL: "http://localhost:3000"

volumes:
  mysql_data:
